### ISSUE TITLE
Current Status Update

### ISSUE THREAD

**Issue by 0mars** [php/pecl-search_engine-solr#36]
I've been sick and been changing countries at the same time, my sincere apologies for being away...

I'm planning to pickup the extension again sometime in the next 2 weeks, since I'm settled now, and feeling better.

Thank you for your patience and continuous support!

Much <3
Omar

**Comment by kwfinken** [comment]
I am glad you are feeling better and settled in! Looking forward to seeing release without PHP8.1 deprecations!

**Comment by bix0r** [comment]
@0mars Hope you are doing good! 

I wonder if you could make a release of this extension?

I have clients that require stable releases of pecl extensions to be allowed to be installed, and many are trying to move to php8.1.

I've been running the `master` branch on all my projects locally with PHP versions 7.4, 8.0 and 8.1.  
No problems so far, except for the issue I reported in August #38, but that is unrelated to the 8.1 update.

ps. If you want help with maintaining this extension I would be more than willing to help.

**Comment by omars1111** [comment]
Hi, apologies to all, but I have lost access to my github, and it will be a long process to get it back, maybe 2-4 weeks. I still have access to pecl

@bix0r Actually your help is so much appreciated, I can grant you access through pecl, but you'll need a php.net account first.

@remicollet do you know who should we contact in order to move forward, and if possible help get access to the github repo.

**Comment by bix0r** [comment]
Wonderful to hear from you @omars1111 !

I have applied for a pecl account.

**Comment by omars44** [comment]
@bix0r Thanks and Welcome :)

Let's work together on reviving the ext
